function latencymgmtoutput = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  LATENCYMGMTOUTPUT = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  LATENCYMGMTOUTPUT = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  latencymgmtoutput = importfile1("C:\Users\danie\Dropbox\UCR\rtenlab\Automatic Latency Management\Evaluation-RTAS\latency_mgmt_output.txt", [3046, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Jan-2025 17:57:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [6046, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [" ", ":"];

% Specify column names and types
opts.VariableNames = ["Thread", "ID", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17"];
opts.SelectedVariableNames = ["Thread", "ID", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10"];
opts.VariableTypes = ["string", "categorical", "double", "string", "double", "categorical", "double", "categorical", "string", "double", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, ["Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Thread", "ID", "VarName3", "VarName6", "VarName7", "VarName8", "VarName10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17"], "EmptyFieldRule", "auto");
%opts = setvaropts(opts, ["VarName4", "VarName9"], "TrimNonNumeric", false);
%opts = setvaropts(opts, ["VarName4", "VarName9"], "ThousandsSeparator", ",");

% Import the data
latencymgmtoutput = readtable(filename, opts);

end